name: Release Windows binaries

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - run: pip install . nuitka
    - name: Build Windows binaries
      run: |
        nuitka --standalone --follow-imports --output-dir=dist/scct_predictions --include-data-dir=.\scct_predictions\templates=templates --include-package-data=scct_predictions -o scct_predictions.exe --remove-output --assume-yes-for-downloads .\scct_predictions\__main__.py
        copy .\windows\* .\dist\scct_predictions
        cd dist
        powershell Compress-Archive scct_predictions scct_predictions-${{github.ref_name }}-windows-amd64.zip
    - name: Upload release artifiacts
      run: |
        gh release upload ${{github.event.release.tag_name}} dist/scct_predictions-${{github.ref_name }}-windows-amd64.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash